export const SESSION_LOGIN_GET = 'SESSION_LOGIN_GET';
export const SESSION_LOGIN_SUCCESS = 'SESSION_LOGIN_SUCCESS';
export const SESSION_LOGIN_ERROR = 'SESSION_LOGIN_ERROR';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_GET = 'REGISTER_GET';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const EMAIL_GET = 'EMAIL_GET';
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS';
export const EMAIL_ERROR = 'EMAIL_ERROR';
export const RESEND_EMAIL_GET = 'RESEND_EMAIL_GET';
export const RESEND_EMAIL_SUCCESS = 'RESEND_EMAIL_SUCCESS';
export const RESEND_EMAIL_ERROR = 'RESEND_EMAIL_ERROR';
export const REGISTER_FORM_GET = 'REGISTER_FORM_GET';
export const REGISTER_FORM_SUCCESS = 'REGISTER_FORM_SUCCESS';
export const REGISTER_FORM_ERROR = 'REGISTER_FORM_ERROR';
export const SMS_GET = 'SMS_GET';
export const SMS_SUCCESS = 'SMS_SUCCESS';
export const SMS_ERROR = 'SMS_ERROR';
export const RESEND_SMS_GET = 'RESEND_SMS_GET';
export const RESEND_SMS_SUCCESS = 'RESEND_SMS_SUCCESS';
export const RESEND_SMS_ERROR = 'RESEND_SMS_ERROR';
